import { motion } from 'framer-motion';
import { ArrowLeft, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const TermsConditions = () => {
  const navigate = useNavigate();

  return (
    <div className="noise-overlay relative min-h-screen flex flex-col" style={{ background: '#08080F' }}>
      <Navbar />

      <main className="flex-grow pt-28 pb-20 max-w-[800px] mx-auto px-6 relative z-10">
        {/* Back navigation */}
        <motion.button
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          onClick={() => navigate('/')}
          className="flex items-center gap-2 text-white/50 hover:text-gold transition-colors font-inter text-xs uppercase tracking-[3px] mb-8 cursor-pointer"
        >
          <ArrowLeft size={14} /> Back to Home
        </motion.button>

        {/* Title */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-12"
        >
          <div className="flex items-center gap-3 text-gold mb-3">
            <FileText size={24} />
            <span className="font-inter text-[11px] uppercase tracking-[4px] font-light">Guidelines & Agreement</span>
          </div>
          <h1 className="font-playfair text-4xl md:text-5xl font-extrabold gold-gradient-text leading-tight">
            Terms & Conditions
          </h1>
          <p className="font-inter text-[13px] text-white/40 mt-3 uppercase tracking-[2px]">
            Effective Date: June 2026
          </p>
        </motion.div>

        {/* Terms Content */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="glass-card-gold p-8 md:p-10 space-y-8 text-white/70 font-inter text-sm md:text-[15px] leading-relaxed"
          style={{ borderRadius: 28 }}
        >
          <div>
            <h2 className="text-white font-semibold text-lg font-playfair mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using JKH Opulence Studio, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with these conditions, you must discontinue the use of our services immediately.
            </p>
          </div>

          <div>
            <h2 className="text-white font-semibold text-lg font-playfair mb-3">2. Service Description & Usage</h2>
            <p>
              JKH Opulence Studio is an interactive, AI-driven home interior layout preview platform. It uses Pollinations AI to perform image transformations. We provide this application completely free of charge to end-users on iOS and web.
            </p>
            <p className="mt-2 text-white/60">
              Users are solely responsible for images uploaded to our system. Do not upload photos containing sensitive personal details, explicit content, or copyrighted imagery belonging to other individuals without their consent.
            </p>
          </div>

          <div>
            <h2 className="text-white font-semibold text-lg font-playfair mb-3">3. High Resolution Export & Licensing</h2>
            <p>
              All designs generated by the JKH Opulence platform are client-owned. You are granted a worldwide, royalty-free, perpetual license to view, share, download, modify, and utilize generated design visuals for both commercial and personal interior decoration projects.
            </p>
          </div>

          <div>
            <h2 className="text-white font-semibold text-lg font-playfair mb-3">4. Limitation of Liability</h2>
            <p>
              AI generations are for mockups, design conceptualization, and visual inspiration. They do not represent final engineering or architectural constructs. JKH Interior holds no liability for construction execution, material differences, or contractor disputes arising from mockups created on this app.
            </p>
          </div>

          <div>
            <h2 className="text-white font-semibold text-lg font-playfair mb-3">5. Variations to Terms</h2>
            <p>
              We reserve the right to modify these terms as our app functionality updates. Continuing to use JKH Opulence after updates have been posted constitutes approval of the new terms.
            </p>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
};

export default TermsConditions;
